import type { Service } from '@/lib/types'

export const services: Service[] = [
  {
    slug: 'pallet-recycling',
    name: 'Pallet Recycling',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Turn used pallets into revenue, not landfill waste.',
    description:
      'Our pallet recycling service collects, sorts, and processes wooden and plastic pallets for reuse or material recovery. We help warehouses, distributors, and manufacturers divert thousands of pallets from landfills each year while reducing disposal costs and supporting circular supply chains.',
    icon: 'inventory_2',
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: 'scrap-metal-recycling',
    name: 'Scrap Metal Recycling',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Get top dollar for ferrous and non-ferrous scrap.',
    description:
      'We buy and process all grades of ferrous and non-ferrous scrap metal, from steel beams and aluminum cans to copper wiring and brass fixtures. Our competitive pricing, transparent grading, and reliable pickup schedules make it easy for businesses to monetize their metal waste streams.',
    icon: 'hardware',
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'electronics-recycling',
    name: 'Electronics Recycling',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Certified e-waste recycling with full data security.',
    description:
      'Dispose of computers, servers, monitors, and other electronic equipment responsibly with our R2-certified e-waste recycling program. We provide chain-of-custody documentation, certified data destruction, and environmentally compliant processing to keep hazardous materials out of landfills.',
    icon: 'memory',
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'material-recycling-solutions',
    name: 'Material Recycling Solutions',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Custom recycling programs for mixed material streams.',
    description:
      'Our material recycling solutions handle complex, multi-material waste streams that standard programs miss. We design custom sorting, baling, and processing workflows tailored to your facility so you can maximize diversion rates and minimize contamination across all recyclable commodities.',
    icon: 'recycling',
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: 'cardboard-paper-recycling',
    name: 'Cardboard & Paper Recycling',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Reliable pickup for OCC, mixed paper, and office waste.',
    description:
      'From OCC bales and office paper to shredded documents and packaging, we provide scheduled collection and processing of all paper and cardboard grades. Our service helps businesses meet sustainability targets while generating rebate value from one of the most commonly recycled materials.',
    icon: 'description',
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: 'plastic-recycling',
    name: 'Plastic Recycling',
    parentSlug: null,
    category: 'core-recycling',
    tagline: 'Reclaim value from plastic scrap, film, and packaging.',
    description:
      'We recycle HDPE, LDPE, PET, PP, and other resin types generated by manufacturing, retail, and distribution operations. Our plastic recycling services include baling, granulating, and connecting your material to domestic and international end markets for maximum commodity return.',
    icon: 'local_drink',
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: 'dumpster-rental',
    name: 'Dumpster Rental',
    parentSlug: null,
    category: 'equipment-logistics',
    tagline: 'Roll-off and front-load dumpsters delivered on your schedule.',
    description:
      'Rent roll-off containers from 10 to 40 cubic yards for construction debris, cleanouts, and large-scale recycling projects. We also offer front-load dumpsters for ongoing commercial waste and recycling needs with flexible pickup frequencies and competitive monthly rates.',
    icon: 'dumpster',
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: 'junk-removal',
    name: 'Junk Removal',
    parentSlug: null,
    category: 'equipment-logistics',
    tagline: 'Fast, eco-friendly removal with maximum diversion.',
    description:
      'Our junk removal crews sort everything on-site, diverting recyclables and donatable items before responsibly disposing of the rest. Whether you are clearing an office, warehouse, or retail space, we handle the heavy lifting and provide documentation of all materials diverted from landfill.',
    icon: 'local_shipping',
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: 'hazardous-waste-disposal',
    name: 'Hazardous Waste Disposal',
    parentSlug: null,
    category: 'specialized',
    tagline: 'Compliant disposal for regulated and hazardous materials.',
    description:
      'We manage the collection, transportation, and disposal of hazardous waste including solvents, batteries, fluorescent lamps, and chemical byproducts. Our licensed team ensures full EPA and state regulatory compliance with manifest tracking, lab packing, and emergency spill response services.',
    icon: 'warning',
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: 'product-destruction',
    name: 'Product Destruction',
    parentSlug: null,
    category: 'specialized',
    tagline: 'Secure destruction with certificates and full chain of custody.',
    description:
      'Protect your brand and intellectual property with our certified product destruction services. We destroy defective goods, expired inventory, recalled products, and proprietary materials with witnessed processing and provide detailed certificates of destruction for your compliance records.',
    icon: 'delete_forever',
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: 'shredding-services',
    name: 'Shredding Services',
    parentSlug: null,
    category: 'specialized',
    tagline: 'NAID-certified shredding for documents, drives, and media.',
    description:
      'Our mobile and plant-based shredding services destroy confidential documents, hard drives, uniforms, and other sensitive materials to NAID AAA standards. We offer scheduled service, one-time purges, and on-site witnessed destruction with certificates of compliance for every job.',
    icon: 'content_cut',
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: 'business-recycling-programs',
    name: 'Business Recycling Programs',
    parentSlug: null,
    category: 'programs',
    tagline: 'Turnkey recycling programs built for your business.',
    description:
      'We design, implement, and manage comprehensive recycling programs for offices, warehouses, and multi-site operations. From container placement and signage to employee training and monthly reporting, our programs drive measurable waste diversion and help you meet corporate sustainability goals.',
    icon: 'business',
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: 'waste-audits-consulting',
    name: 'Waste Audits & Consulting',
    parentSlug: null,
    category: 'programs',
    tagline: 'Data-driven insights to cut waste costs and boost diversion.',
    description:
      'Our waste audit and consulting services analyze your current waste streams, hauling contracts, and diversion rates to identify cost savings and improvement opportunities. We deliver actionable recommendations backed by data so you can reduce spend, increase recycling, and stay ahead of regulations.',
    icon: 'query_stats',
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: 'collection-events',
    name: 'Collection Events',
    parentSlug: null,
    category: 'programs',
    tagline: 'Community and corporate recycling events, fully managed.',
    description:
      'We plan and staff turnkey collection events for hard-to-recycle items like electronics, tires, mattresses, and household hazardous waste. Our team handles permitting, logistics, staffing, and post-event reporting so municipalities and corporations can engage their communities in responsible recycling.',
    icon: 'event',
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: 'take-back-programs',
    name: 'Take-Back Programs',
    parentSlug: null,
    category: 'programs',
    tagline: 'EPR-ready take-back logistics for product stewardship.',
    description:
      'Meet extended producer responsibility requirements with our managed take-back programs. We set up collection points, reverse logistics, and end-of-life processing for packaging, electronics, batteries, and other regulated products so your brand stays compliant and consumers have an easy return path.',
    icon: 'assignment_return',
    isActive: true,
    sortOrder: 15,
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug)
}
